apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarqube
  namespace: dev
  labels:
    app: sonarqube
spec:
  serviceName: sonarqube
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 1000
      # SonarQube needs higher kernel limits for Elasticsearch
      initContainers:
        - name: increase-vm-max-map
          image: busybox:1.36
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=524288 && sysctl -w fs.file-max=131072']
          securityContext:
            privileged: true
      containers:
        - name: sonarqube
          image: sonarqube:latest
          imagePullPolicy: Always
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://postgres.dev.svc.cluster.local:5432/sonarqube"
            - name: SONAR_JDBC_USERNAME
              value: "sonaruser"
            - name: SONAR_JDBC_PASSWORD
              value: "ChangeThisPassword!"
            - name: SONAR_WEB_JAVAOPTS
              value: "-Xms512m -Xmx512m"
            - name: SONAR_ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
          ports:
            - name: http
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/system/status
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "2.5Gi"
            limits:
              cpu: "1"
              memory: "3.5Gi"
          volumeMounts:
            - name: sonarqube-data
              mountPath: /opt/sonarqube/data
            - name: sonarqube-extensions
              mountPath: /opt/sonarqube/extensions
            - name: sonarqube-logs
              mountPath: /opt/sonarqube/logs
  volumeClaimTemplates:
    - metadata:
        name: sonarqube-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: sonarqube-extensions
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: sonarqube-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 2Gi
