apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sonarqube-gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
