apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium", "t3.large", "m5.large"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
  limits:
    resources:
      cpu: 1000
      memory: 4000Gi
  provider:
    subnetSelector:
      karpenter.sh/discovery: demo-cluster
    securityGroupSelector:
      karpenter.sh/discovery: demo-cluster
  consolidation:
    enabled: true
  ttlSecondsAfterEmpty: 120
