apiVersion: v1
kind: Namespace
metadata:
  name: mylera
  labels:
    app: mylera
    owner: platform
    env: production

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mylera-quota
  namespace: mylera
spec:
  hard:
    requests.cpu: "30"
    requests.memory: "60Gi"
    limits.cpu: "60"
    limits.memory: "120Gi"
    persistentvolumeclaims: "5"
    pods: "150"
    services: "30"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mylera-network-policy
  namespace: mylera
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              app: mylera
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 5432
    - to:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

---
apiVersion: v1
kind: LimitRange
metadata:
  name: mylera-limit-range
  namespace: mylera
spec:
  limits:
    - max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "128Mi"
      type: Container
    - max:
        cpu: "4"
        memory: "8Gi"
      type: Pod
