apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-sqs-scaler
  namespace: dev
  labels:
    app: backend
spec:
  scaleTargetRef:
    name: node-mylera
    kind: Deployment
  minReplicaCount: 2
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 300
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 30
            - type: Pods
              value: 2
              periodSeconds: 30
          selectPolicy: Max
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/123456789012/demo-queue
        awsRegion: us-east-1
        queueLength: "5"
        identityOwner: operator
        awsAuthorization: irsa

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sonarqube-cpu-scaler
  namespace: dev
  labels:
    app: sonarqube
spec:
  scaleTargetRef:
    name: sonarqube
    kind: StatefulSet
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 15
  cooldownPeriod: 180
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
